version: '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --innodb-buffer-pool-size=64M --max-connections=20
    environment:
      MYSQL_ROOT_PASSWORD: Uday@1234
      MYSQL_DATABASE: employee_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend/employee-backend
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  frontend:
    build: ./backend/frontend
    ports:
      - "8082:80"
    depends_on:
      - backend

volumes:
  mysql_data: